/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrialInternalRouteImport } from './routes/trial_.internal'
import { Route as RInternalIosRouteImport } from './routes/r.internal.ios'
import { Route as RInternalAndroidRouteImport } from './routes/r.internal.android'
import { Route as RExternalIosRouteImport } from './routes/r.external.ios'
import { Route as RExternalAndroidRouteImport } from './routes/r.external.android'

const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialInternalRoute = TrialInternalRouteImport.update({
  id: '/trial_/internal',
  path: '/trial/internal',
  getParentRoute: () => rootRouteImport,
} as any)
const RInternalIosRoute = RInternalIosRouteImport.update({
  id: '/r/internal/ios',
  path: '/r/internal/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const RInternalAndroidRoute = RInternalAndroidRouteImport.update({
  id: '/r/internal/android',
  path: '/r/internal/android',
  getParentRoute: () => rootRouteImport,
} as any)
const RExternalIosRoute = RExternalIosRouteImport.update({
  id: '/r/external/ios',
  path: '/r/external/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const RExternalAndroidRoute = RExternalAndroidRouteImport.update({
  id: '/r/external/android',
  path: '/r/external/android',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trial': typeof TrialRoute
  '/trial/internal': typeof TrialInternalRoute
  '/r/external/android': typeof RExternalAndroidRoute
  '/r/external/ios': typeof RExternalIosRoute
  '/r/internal/android': typeof RInternalAndroidRoute
  '/r/internal/ios': typeof RInternalIosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trial': typeof TrialRoute
  '/trial/internal': typeof TrialInternalRoute
  '/r/external/android': typeof RExternalAndroidRoute
  '/r/external/ios': typeof RExternalIosRoute
  '/r/internal/android': typeof RInternalAndroidRoute
  '/r/internal/ios': typeof RInternalIosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trial': typeof TrialRoute
  '/trial_/internal': typeof TrialInternalRoute
  '/r/external/android': typeof RExternalAndroidRoute
  '/r/external/ios': typeof RExternalIosRoute
  '/r/internal/android': typeof RInternalAndroidRoute
  '/r/internal/ios': typeof RInternalIosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trial'
    | '/trial/internal'
    | '/r/external/android'
    | '/r/external/ios'
    | '/r/internal/android'
    | '/r/internal/ios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trial'
    | '/trial/internal'
    | '/r/external/android'
    | '/r/external/ios'
    | '/r/internal/android'
    | '/r/internal/ios'
  id:
    | '__root__'
    | '/'
    | '/trial'
    | '/trial_/internal'
    | '/r/external/android'
    | '/r/external/ios'
    | '/r/internal/android'
    | '/r/internal/ios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrialRoute: typeof TrialRoute
  TrialInternalRoute: typeof TrialInternalRoute
  RExternalAndroidRoute: typeof RExternalAndroidRoute
  RExternalIosRoute: typeof RExternalIosRoute
  RInternalAndroidRoute: typeof RInternalAndroidRoute
  RInternalIosRoute: typeof RInternalIosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial_/internal': {
      id: '/trial_/internal'
      path: '/trial/internal'
      fullPath: '/trial/internal'
      preLoaderRoute: typeof TrialInternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/internal/ios': {
      id: '/r/internal/ios'
      path: '/r/internal/ios'
      fullPath: '/r/internal/ios'
      preLoaderRoute: typeof RInternalIosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/internal/android': {
      id: '/r/internal/android'
      path: '/r/internal/android'
      fullPath: '/r/internal/android'
      preLoaderRoute: typeof RInternalAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/external/ios': {
      id: '/r/external/ios'
      path: '/r/external/ios'
      fullPath: '/r/external/ios'
      preLoaderRoute: typeof RExternalIosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/external/android': {
      id: '/r/external/android'
      path: '/r/external/android'
      fullPath: '/r/external/android'
      preLoaderRoute: typeof RExternalAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrialRoute: TrialRoute,
  TrialInternalRoute: TrialInternalRoute,
  RExternalAndroidRoute: RExternalAndroidRoute,
  RExternalIosRoute: RExternalIosRoute,
  RInternalAndroidRoute: RInternalAndroidRoute,
  RInternalIosRoute: RInternalIosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
